services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: chess
      POSTGRES_PASSWORD: chesspw
      POSTGRES_DB: chessdb
      ports: 5432
      volumes: pgdata:/var/lib/postgresql/data
volumes:
  pgdata: